version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /root/dockerapps/configs/sonarr:/config
      - /home/amirulandalib/downloads/media/tv:/tv #optional
      - /home/amirulandalib/downloads/qbittorrent/sonarr:/downloads #optional
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8989:8989
    