version: "3.7"

services:
  qbittorrent:
    container_name: qbittorrent
    image: cr.hotio.dev/hotio/qbittorrent
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      - 9001:9001
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - WEBUI_PORT=8080
      - UMASK=000
    volumes:
      - /root/dockerapps/configs/qbittorrent:/config
      - /home/amirulandalib/downloads/qbittorrent:/downloads
      - /var/run/docker.sock:/var/run/docker.sock
    
