version: "2.1"
services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /root/dockerapps/configs/pyload:/config
      - /home/amirulandalib/downloads/pyload:/downloads
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
      #- 9666:9666 #optional