version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:nightly
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /root/dockerapps/configs/prowlarr:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9696:9696
    
