version: '3.5'
services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 1000:1000
    volumes:
      - /root/dockerapps/configs/recyclarr:/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Pacific/Auckland
      - PUID=1000
      - PGID=1000
