version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:nightly
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /root/dockerapps/configs/radarr:/config
      - /home/amirulandalib/downloads/media/movies:/movies #optional
      - /home/amirulandalib/downloads/qbittorrent/radarr:/downloads #optional
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7878:7878
    