version: '3.5'

services:
  dash:
    image: mauricenino/dashdot:latest
    container_name: dashdot
    
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - '3001:3001'
    volumes:
      - /:/mnt/host:ro
